tools:
  - name: asknews_impact
    module: tools.asknews_tool
    object: AskNewsImpactTool
    enabled: true
    phases: [data_gather, signal_generation]
  - name: tvl_growth
    module: tools.tvl_tool
    object: TVLGrowthTool
    enabled: true
    phases: [data_gather, feature_engineering]
  - name: volatility_percentile
    module: tools.volatility_tool
    object: VolatilityPercentileTool
    enabled: true
    phases: [feature_engineering, risk_sizing]
